m1 = int(input('Número de moedas de 1 centavo: '))
m5 = int(input('Número de moedas de 5 centavos: '))
m10 = int(input('Número de moedas de 10 centavos: '))
m25 = int(input('Número de moedas de 25 centavos: '))
m50 = int(input('Número de moedas de 50 centavos: '))
m100 = int(input('Número de moedas de 1 real: '))
resultado = float((m1 + m5 * 5 + m10 * 10 + m25 * 25 + m50 * 50 + m100)/100)
print('O valor economizado foi de {}'.format(resultado))
print(resultado)
